name: Release

on:
  push:
    tags: ["v*"]

jobs:
  create-release:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build-model:
    needs: ["create-release"]
    permissions: write-all
    name: Build the model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Build module
        run: $HOME/.rokit/bin/rojo build --output module.rbxm model.project.json

      - name: Upload module to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: module.rbxm
          asset_name: module.rbxm
          asset_content_type: application/octet-stream

      - name: Upload module to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: module.rbxm
          path: module.rbxm

      - name: Build place
        run: $HOME/.rokit/bin/rojo build --output ExamplePlace.rbxl ./default.project.json
      
      - name: Upload place to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ExamplePlace.rbxl
          asset_name: ExamplePlace.rbxl
          asset_content_type: application/octet-stream

      - name: Upload place to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExamplePlace.rbxl
          path: ExamplePlace.rbxl